sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

language: scala

jdk:
  - openjdk8

env:
  - CODACY_PROJECT_TOKEN=e0672985af4742b38ee4143d00ca8253

script:
  - sbt clean coverage test scalastyle
  - sbt coverageAggregate

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coveralls
  - sbt ++$TRAVIS_SCALA_VERSION codacyCoverage
   # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm -f
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm -f


